unit ChsDet.Corpus;

interface

uses
  System.Generics.Collections,
  System.SysUtils,
  ChsDet.EncodingDetector;

type
  TChsCorpusTier = (ctStrict, ctInformational);

  TChsCorpusCase = record
    Tier: TChsCorpusTier;
    Family: string;
    FileName: string;
    ExpectedCodePage: Integer;
    ExpectedName: string;
    Notes: string;
  end;

  TChsCorpusResult = record
    CaseInfo: TChsCorpusCase;
    Detection: TChsDetectionResult;
    IsExactMatch: Boolean;
  end;

  TChsCorpus = record
  public
    class function RepoRoot: string; static;
    class function CorpusDir: string; static;
    class function DataDir: string; static;
    class function ManifestPath: string; static;
    class function MatrixPath: string; static;
    class function LoadCases: TArray<TChsCorpusCase>; static;
    class function RunAll: TArray<TChsCorpusResult>; static;
    class function BuildMarkdownMatrix(const Results: TArray<TChsCorpusResult>): string; static;
    class function StrictFailureCount(const Results: TArray<TChsCorpusResult>): Integer; static;
  end;

implementation

uses
  System.Classes,
  System.IOUtils;

class function TChsCorpus.RepoRoot: string;
var
  Candidate: string;
begin
  Candidate := ExcludeTrailingPathDelimiter(ExtractFilePath(ParamStr(0)));
  while Candidate <> '' do
  begin
    if TFile.Exists(TPath.Combine(Candidate, TPath.Combine('tests', TPath.Combine('corpus', 'manifest.tsv')))) then
      Exit(Candidate);

    if SameText(ExtractFileDrive(Candidate), Candidate) then
      Break;

    Candidate := ExcludeTrailingPathDelimiter(ExtractFileDir(Candidate));
  end;

  raise EFileNotFoundException.Create('Unable to locate repository root from executable path.');
end;

class function TChsCorpus.CorpusDir: string;
begin
  Result := TPath.Combine(RepoRoot, TPath.Combine('tests', 'corpus'));
end;

class function TChsCorpus.DataDir: string;
begin
  Result := TPath.Combine(CorpusDir, 'data');
end;

class function TChsCorpus.ManifestPath: string;
begin
  Result := TPath.Combine(CorpusDir, 'manifest.tsv');
end;

class function TChsCorpus.MatrixPath: string;
begin
  Result := TPath.Combine(CorpusDir, 'MATRIX.md');
end;

class function TChsCorpus.LoadCases: TArray<TChsCorpusCase>;
var
  Lines: TStringList;
  Cases: TList<TChsCorpusCase>;
  Parts: TArray<string>;
  I: Integer;
  Item: TChsCorpusCase;
begin
  Lines := TStringList.Create;
  Cases := TList<TChsCorpusCase>.Create;
  try
    Lines.LoadFromFile(ManifestPath, TEncoding.UTF8);
    for I := 1 to Lines.Count - 1 do
    begin
      if Trim(Lines[I]) = '' then
        Continue;

      Parts := Lines[I].Split([#9]);
      if Length(Parts) < 6 then
        raise EInvalidOpException.CreateFmt('Invalid corpus manifest row %d.', [I + 1]);

      if SameText(Parts[0], 'strict') then
        Item.Tier := ctStrict
      else if SameText(Parts[0], 'informational') then
        Item.Tier := ctInformational
      else
        raise EInvalidOpException.CreateFmt('Unknown corpus tier "%s" on row %d.', [Parts[0], I + 1]);

      Item.Family := Parts[1];
      Item.FileName := Parts[2];
      Item.ExpectedCodePage := StrToInt(Parts[3]);
      Item.ExpectedName := Parts[4];
      Item.Notes := Parts[5];
      Cases.Add(Item);
    end;

    Result := Cases.ToArray;
  finally
    Cases.Free;
    Lines.Free;
  end;
end;

class function TChsCorpus.RunAll: TArray<TChsCorpusResult>;
var
  Cases: TArray<TChsCorpusCase>;
  I: Integer;
begin
  Cases := LoadCases;
  SetLength(Result, Length(Cases));
  for I := 0 to High(Cases) do
  begin
    Result[I].CaseInfo := Cases[I];
    Result[I].Detection := TChsEncodingDetector.DetectFile(TPath.Combine(DataDir, Cases[I].FileName));
    Result[I].IsExactMatch :=
      (Result[I].Detection.CodePage = Cases[I].ExpectedCodePage) and
      SameText(Result[I].Detection.Name, Cases[I].ExpectedName);
  end;
end;

class function TChsCorpus.StrictFailureCount(const Results: TArray<TChsCorpusResult>): Integer;
var
  Item: TChsCorpusResult;
begin
  Result := 0;
  for Item in Results do
    if (Item.CaseInfo.Tier = ctStrict) and (not Item.IsExactMatch) then
      Inc(Result);
end;

class function TChsCorpus.BuildMarkdownMatrix(const Results: TArray<TChsCorpusResult>): string;
var
  Builder: TStringBuilder;
  Item: TChsCorpusResult;
  StrictCount: Integer;
  StrictPassed: Integer;
  InfoCount: Integer;
  InfoExact: Integer;
  StatusText: string;
  TierText: string;
  Invariant: TFormatSettings;
begin
  Invariant := TFormatSettings.Invariant;
  StrictCount := 0;
  StrictPassed := 0;
  InfoCount := 0;
  InfoExact := 0;

  Builder := TStringBuilder.Create;
  try
    Builder.AppendLine('# Corpus Matrix');
    Builder.AppendLine;
    Builder.AppendLine('Generated by `ChsDetCorpusBench.dpr`.');
    Builder.AppendLine;

    for Item in Results do
    begin
      case Item.CaseInfo.Tier of
        ctStrict:
          begin
            Inc(StrictCount);
            if Item.IsExactMatch then
              Inc(StrictPassed);
          end;
        ctInformational:
          begin
            Inc(InfoCount);
            if Item.IsExactMatch then
              Inc(InfoExact);
          end;
      end;
    end;

    Builder.AppendLine(Format('- Strict cases: `%d/%d` exact matches', [StrictPassed, StrictCount]));
    Builder.AppendLine(Format('- Informational cases: `%d/%d` exact matches', [InfoExact, InfoCount]));
    Builder.AppendLine;
    Builder.AppendLine('| Tier | Family | Fixture | Expected | Detected | Confidence | Status | Notes |');
    Builder.AppendLine('| --- | --- | --- | --- | --- | ---: | --- | --- |');

    for Item in Results do
    begin
      if Item.CaseInfo.Tier = ctStrict then
      begin
        TierText := 'strict';
        if Item.IsExactMatch then
          StatusText := 'PASS'
        else
          StatusText := 'FAIL';
      end
      else
      begin
        TierText := 'informational';
        if Item.IsExactMatch then
          StatusText := 'INFO-PASS'
        else
          StatusText := 'INFO-MISS';
      end;

      Builder.AppendLine(Format(
        '| %s | %s | `%s` | `%s / %d` | `%s / %d` | %.4f | %s | %s |',
        [TierText,
         Item.CaseInfo.Family,
         Item.CaseInfo.FileName,
         Item.CaseInfo.ExpectedName,
         Item.CaseInfo.ExpectedCodePage,
         Item.Detection.Name,
         Item.Detection.CodePage,
         Item.Detection.Confidence,
         StatusText,
         Item.CaseInfo.Notes],
        Invariant
      ));
    end;

    Result := Builder.ToString;
  finally
    Builder.Free;
  end;
end;

end.
